# Site settings
title: RCAIDE_LEADS
email: your-email@domain.com
description: >
  RCAIDE_LEADS is a simple, user-friendly static site generator. It takes a template
lang: en-US

baseurl: "" # Leave empty unless your site is in a subdirectory
url: "" # Base URL, e.g., https://your-site.com

# Minimal Mistakes-specific settings
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single

collections:
  docs:
    output: true
    permalink: /:collection/:path/

  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Optional settings
timezone: America/New_York
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
